version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - php
      - db

  php:
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    env_file:
      - .env

  db:
    image: mysql:5.6
    tty: true
    ports:
      - "3305:${DB_PORT}"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./.docker/db:/var/lib/mysql/
    networks:
      - laravel
